apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-state-metrics-configmap
  namespace: default
data:
  conf.yaml: |-
    init_config:
    instances:
      - kube_state_url: http://%%host%%:8080/metrics


