apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      containers:
      - image: datadog/agent:7
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            # Custom metrics via DogStatsD - uncomment this section to enable custom metrics collection
            hostPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            # Trace Collection (APM) - uncomment this section to enable APM
            hostPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TAGS
            value: "owner:et cloud_provider:onprem"
          - name: DD_APM_ENABLED
            value: "true"
          - name: DD_HOSTNAME
            value: "raspberrypi"
          - name: DD_APM_NON_LOCAL_TRAFFIC
            value: "true"
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: KUBERNETES
            value: "true"
          - name: DD_KUBELET_TLS_VERIFY
            value: "false"
          - name: DD_HEALTH_PORT
            value: "5555"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: syslog
            mountPath: /var/log/syslog
          - name: pointdir
            mountPath: /opt/datadog-agent/run
          - name: logpodpath
            mountPath: /var/log/pod
          - name: logcontainerpath
            mountPath: /var/lib/docker/containers
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: kube-scheduler-config
            mountPath: /etc/datadog-agent/conf.d/kube_scheduler.d
          - name: kube-ctrl-mgr-config
            mountPath: /etc/datadog-agent/conf.d/kube_controller_manager.d
          - name: etcd-config
            mountPath: /etc/datadog-agent/conf.d/etcd.d
          - name: etcd-pki
            mountPath: /etc/kubernetes/pki/etcd/
          - name: kube-apiserver-metrics-config
            mountPath: /etc/datadog-agent/conf.d/kube_apiserver_metrics.d
          - name: syslog-config
            mountPath: /etc/datadog-agent/conf.d/ubuntu.d
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - hostPath:
            path: /var/log/syslog
          name: syslog
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        - hostPath:
            path: /var/lib/docker/containers
          name: logcontainerpath
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointdir
        - hostPath:
            path: /etc/kubernetes/pki/etcd
          name: etcd-pki
        - name: syslog-config
          configMap:
            name: syslog-configmap
        - name: kube-scheduler-config
          configMap:
            name: kube-scheduler-configmap
        - name: kube-ctrl-mgr-config
          configMap:
            name: kube-ctrl-mgr-configmap
        - name: etcd-config
          configMap:
            name: etcd-configmap
        - name: kube-apiserver-metrics-config
          configMap:
            name: kube-apiserver-metrics-configmap
